ame: CI
on:
  push:
    branches:
      -master
  pull_request:
    branches:
      - master
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '22'
    
    - name: Install dependencies
      run: |  
        npm install
    
    - name: Run tests
      run: |
        npm test
